import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import importPlugin from 'eslint-plugin-import';

// Flat config, replacing .eslintrc.json.
// -----------------------------------------------------------------------
// `pnpm lint` failed in all thirteen packages with
//
//   ESLint couldn't find an eslint.config.(js|mjs|cjs) file.
//
// The repository declares eslint ^9.10.0 and had a v8 `.eslintrc.json`,
// which ESLint 9 does not read, and every package script passed `--ext
// .ts`, which ESLint 9 removed. So linting had never run on a single
// file — the same shape of failure as the CI workflow sitting outside
// .github/workflows/, and of the migration chain that could not apply.
//
// The rules below are the ones .eslintrc.json declared. This is a port,
// not a re-think: changing what is enforced at the same time as fixing
// why nothing was enforced would make it impossible to tell which
// findings are new rules and which are real.
// -----------------------------------------------------------------------

export default [
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.ts',
      // Generated by `prisma generate`, not written by anyone here.
      'packages/db/generated/**',
    ],
  },

  js.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],

    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
    },

    plugins: {
      '@typescript-eslint': tsPlugin,
      import: importPlugin,
    },

    rules: {
      ...tsPlugin.configs.recommended.rules,

      // TypeScript resolves identifiers itself and reports unknown ones
      // as compile errors, so `no-undef` here adds nothing and
      // misreports every ambient and DOM global. Disabling it for TS is
      // what typescript-eslint's own recommended config does, and it is
      // why this file needs no `globals` package.
      'no-undef': 'off',

      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',

      'import/order': [
        'warn',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],

      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    // Tests say what they are doing out loud, and a fixture that types a
    // deliberately wrong shape is the test.
    files: ['**/*.test.ts', '**/*.test.tsx', 'tests/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    // The observability logger IS the console boundary; forbidding
    // console there would forbid it from doing its job.
    files: ['packages/observability/src/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    // Scripts are operator tooling. Printing is the point.
    files: ['scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
];
