-- =========================================================================
-- Initial migration.
--
-- Hand-authored (not machine-generated by `prisma migrate dev`) because
-- this environment's network sandbox cannot reach binaries.prisma.sh to
-- fetch Prisma's schema-engine binary, which `migrate dev` requires to
-- diff and generate migrations. This file was derived by hand, field for
-- field, from prisma/schema.prisma, and was validated by actually
-- applying it to a real PostgreSQL 16 instance and running integration
-- tests against it (see /tests/integration).
--
-- ACTION REQUIRED before treating this as final: run `prisma migrate dev`
-- once in a normal networked environment. It should report the schema
-- and migration history are in sync (no drift). If it proposes any
-- changes, that means this hand-authored SQL diverged from Prisma's own
-- output somewhere — trust prisma migrate dev's version at that point.
--
-- This migration also includes the two constraints noted in
-- schema.prisma as inexpressible in Prisma's schema language:
--   1. CHECK (amount_paise > 0) on orders and payments.
--   2. Partial unique index on payments: one CAPTURED payment per order.
-- =========================================================================

-- ---- Enums ----

CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'ATTEMPTED', 'PAID', 'FAILED', 'EXPIRED');
CREATE TYPE "PaymentStatus" AS ENUM ('AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED');
CREATE TYPE "MetaEventStatus" AS ENUM ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'DEAD_LETTER');
CREATE TYPE "IdempotencyRecordType" AS ENUM ('ORDER', 'PAYMENT', 'WEBHOOK_EVENT', 'META_EVENT');
CREATE TYPE "IdempotencyReconciliationStatus" AS ENUM ('OPEN', 'IN_REVIEW', 'RESOLVED', 'IGNORED');
CREATE TYPE "ProductionIndexMigrationStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK');

-- ---- orders ----

CREATE TABLE "orders" (
    "id"               TEXT NOT NULL,
    "razorpay_order_id" TEXT NOT NULL,
    "idempotency_key"  TEXT,
    "customer_name"    TEXT,
    "customer_email"   TEXT NOT NULL,
    "customer_phone"   TEXT,
    "product_slug"     TEXT NOT NULL,
    "product_name"     TEXT NOT NULL,
    "amount_paise"     INTEGER NOT NULL,
    "currency"         TEXT NOT NULL DEFAULT 'INR',
    "status"           "OrderStatus" NOT NULL DEFAULT 'PENDING',
    "created_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id"),
    -- Not natively expressible in Prisma schema language (see header note).
    CONSTRAINT "orders_amount_paise_positive" CHECK ("amount_paise" > 0)
);

CREATE UNIQUE INDEX "orders_razorpay_order_id_key" ON "orders"("razorpay_order_id");
CREATE UNIQUE INDEX "orders_idempotency_key_key" ON "orders"("idempotency_key");
CREATE INDEX "orders_customer_email_idx" ON "orders"("customer_email");
CREATE INDEX "orders_status_idx" ON "orders"("status");
CREATE INDEX "orders_product_slug_idx" ON "orders"("product_slug");

-- ---- payments ----

CREATE TABLE "payments" (
    "id"                        TEXT NOT NULL,
    "razorpay_payment_id"       TEXT NOT NULL,
    "order_id"                  TEXT NOT NULL,
    "amount_paise"              INTEGER NOT NULL,
    "currency"                  TEXT NOT NULL DEFAULT 'INR',
    "status"                    "PaymentStatus" NOT NULL,
    "created_at"                TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"                TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "payments_amount_paise_positive" CHECK ("amount_paise" > 0)
);

CREATE UNIQUE INDEX "payments_razorpay_payment_id_key" ON "payments"("razorpay_payment_id");
CREATE INDEX "payments_order_id_idx" ON "payments"("order_id");
CREATE INDEX "payments_status_idx" ON "payments"("status");

-- Not natively expressible in Prisma schema language: only one CAPTURED
-- payment per order (see architecture §4.2, §14 item 12).
CREATE UNIQUE INDEX "payments_one_captured_per_order"
    ON "payments"("order_id")
    WHERE "status" = 'CAPTURED';

ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_fkey"
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---- webhook_events ----

CREATE TABLE "webhook_events" (
    "id"                TEXT NOT NULL,
    "provider"          TEXT NOT NULL DEFAULT 'razorpay',
    "razorpay_event_id" TEXT NOT NULL,
    "event_name"        TEXT NOT NULL,
    "order_id"          TEXT,
    "payload"           JSONB NOT NULL,
    "signature_valid"   BOOLEAN NOT NULL,
    "received_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at"      TIMESTAMP(3),
    "processing_error"  TEXT,
    "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"        TIMESTAMP(3) NOT NULL,

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "webhook_events_razorpay_event_id_key" ON "webhook_events"("razorpay_event_id");
CREATE INDEX "webhook_events_order_id_idx" ON "webhook_events"("order_id");
CREATE INDEX "webhook_events_event_name_idx" ON "webhook_events"("event_name");
CREATE INDEX "webhook_events_processed_at_idx" ON "webhook_events"("processed_at");

ALTER TABLE "webhook_events" ADD CONSTRAINT "webhook_events_order_id_fkey"
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---- meta_events ----

CREATE TABLE "meta_events" (
    "id"               TEXT NOT NULL,
    "meta_event_id"    TEXT NOT NULL,
    "order_id"         TEXT NOT NULL,
    "event_name"       TEXT NOT NULL,
    "product"          TEXT NOT NULL,
    "value_paise"      INTEGER NOT NULL,
    "currency"         TEXT NOT NULL DEFAULT 'INR',
    "status"           "MetaEventStatus" NOT NULL DEFAULT 'PENDING',
    "attempts"         INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lease_owner"      TEXT,
    "lease_expires_at" TIMESTAMP(3),
    "last_error"       TEXT,
    "created_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       TIMESTAMP(3) NOT NULL,

    CONSTRAINT "meta_events_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "meta_events_meta_event_id_key" ON "meta_events"("meta_event_id");
CREATE INDEX "meta_events_status_next_attempt_at_idx" ON "meta_events"("status", "next_attempt_at");
CREATE INDEX "meta_events_order_id_idx" ON "meta_events"("order_id");
CREATE INDEX "meta_events_lease_expires_at_idx" ON "meta_events"("lease_expires_at");

ALTER TABLE "meta_events" ADD CONSTRAINT "meta_events_order_id_fkey"
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---- idempotency_reconciliations ----

CREATE TABLE "idempotency_reconciliations" (
    "id"            TEXT NOT NULL,
    "record_type"   "IdempotencyRecordType" NOT NULL,
    "duplicate_key" TEXT NOT NULL,
    "snapshot"      JSONB NOT NULL,
    "record_count"  INTEGER NOT NULL,
    "status"        "IdempotencyReconciliationStatus" NOT NULL DEFAULT 'OPEN',
    "resolution"    TEXT,
    "resolved_by"   TEXT,
    "created_at"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"    TIMESTAMP(3) NOT NULL,

    CONSTRAINT "idempotency_reconciliations_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "idempotency_reconciliation_unique_case"
    ON "idempotency_reconciliations"("record_type", "duplicate_key");
CREATE INDEX "idempotency_reconciliations_status_idx" ON "idempotency_reconciliations"("status");

-- ---- production_index_migrations ----

CREATE TABLE "production_index_migrations" (
    "id"                TEXT NOT NULL,
    "migration_name"    TEXT NOT NULL,
    "index_name"        TEXT NOT NULL,
    "deployment_status" "ProductionIndexMigrationStatus" NOT NULL DEFAULT 'PENDING',
    "start_time"        TIMESTAMP(3),
    "completion_time"   TIMESTAMP(3),
    "error"             TEXT,
    "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"        TIMESTAMP(3) NOT NULL,

    CONSTRAINT "production_index_migrations_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "production_index_migration_unique"
    ON "production_index_migrations"("migration_name", "index_name");
CREATE INDEX "production_index_migrations_status_idx" ON "production_index_migrations"("deployment_status");
