import { RazorpaySignatureConfigError, verifyRazorpayWebhookSignature } from './razorpaySignature';

// The webhook trust boundary.
// -----------------------------------------------------------------------
// This file exists to make one ordering impossible to get wrong:
//
//   raw bytes -> verify HMAC -> parse JSON -> persist -> process
//
// Every step depends on the one before it, and the dependency is carried
// in the TYPES rather than in a comment. `handleRazorpayWebhook` does not
// accept a body; it accepts a `VerifiedWebhook`, and the only way to
// obtain one is `verifyRazorpayWebhook`. A future implementer who parses
// first and verifies later cannot call the handler with what they have —
// it is a compile error, not a code review finding.
//
// WHY THAT MATTERS MORE THAN IT LOOKS: this endpoint is architecturally
// defined as the single source of payment truth. A handler that trusts an
// unverified body grants entitlements to anyone who can POST JSON. The
// previous shape of this code had a fully-written verifier with zero
// production call sites and a route that returned 501 — the control was
// correct and unreachable, which is the same as absent the moment someone
// writes the handler.
// -----------------------------------------------------------------------

/**
 * Why a request was refused. A closed set, and our classification — never
 * anything read out of the request.
 */
export type WebhookRejectionReason =
  | 'missing-signature'
  | 'malformed-signature'
  | 'bad-signature'
  | 'empty-body'
  | 'body-too-large';

/**
 * Razorpay payloads are small. The cap exists so an unauthenticated
 * request cannot make us hash — or hold in memory — an arbitrary amount
 * of data before we have any reason to trust the sender.
 */
export const MAX_WEBHOOK_BODY_BYTES = 1_048_576; // 1 MiB

/** Brand. Not exported, so no other module can forge the marker. */
declare const VERIFIED_BRAND: unique symbol;

/**
 * A request whose HMAC has been checked against the raw bytes.
 *
 * The brand is unforgeable outside this module, so possession of one of
 * these is proof that verification happened — and the handler's signature
 * demands one.
 */
export interface VerifiedWebhook {
  readonly [VERIFIED_BRAND]: true;
  /** The exact bytes the signature was computed over. */
  readonly rawBody: Buffer;
  readonly receivedAt: Date;
}

/**
 * Metadata about a refused request, safe to persist.
 *
 * Everything here is either generated by us or a bounded measurement.
 * There is deliberately no field for the body, the signature value, or
 * anything parsed out of the payload: on a rejected request all of that
 * is attacker-chosen, and an event id read from an unverified body is not
 * an event id, it is a string somebody sent us.
 */
export interface WebhookRejection {
  reason: WebhookRejectionReason;
  receivedAt: Date;
  bodyBytes: number;
  signaturePresent: boolean;
  signatureWellFormed: boolean;
  sourceIp?: string | undefined;
}

export type WebhookVerification =
  | { ok: true; verified: VerifiedWebhook }
  | { ok: false; rejection: WebhookRejection };

const SHA256_HEX = /^[0-9a-f]{64}$/i;

export interface VerifyWebhookInput {
  /** The RAW request body. Never a parsed object, never re-serialised. */
  rawBody: Buffer;
  /** The X-Razorpay-Signature header, or null when absent. */
  signatureHeader: string | null | undefined;
  webhookSecret: string;
  receivedAt?: Date;
  /** Network metadata for the rejection record, if the edge supplies it. */
  sourceIp?: string | undefined;
}

/**
 * The only door into webhook processing.
 *
 * Returns a discriminated result rather than throwing, because "someone
 * sent us an unsigned request" is ordinary internet traffic, not an
 * exceptional condition. A missing secret still throws — that is a
 * deployment fault and must not be mistaken for a rejected attacker.
 */
export function verifyRazorpayWebhook(input: VerifyWebhookInput): WebhookVerification {
  const receivedAt = input.receivedAt ?? new Date();
  const header = typeof input.signatureHeader === 'string' ? input.signatureHeader : null;
  const signaturePresent = header !== null && header.length > 0;
  const signatureWellFormed = signaturePresent && SHA256_HEX.test(header);
  const bodyBytes = Buffer.isBuffer(input.rawBody) ? input.rawBody.byteLength : 0;

  const base = {
    receivedAt,
    bodyBytes,
    signaturePresent,
    signatureWellFormed,
    ...(input.sourceIp !== undefined ? { sourceIp: input.sourceIp } : {}),
  };

  if (!input.webhookSecret) {
    // Configuration, not traffic. Failing closed here would silently
    // reject every real webhook and look identical to an attack.
    throw new RazorpaySignatureConfigError(
      'verifyRazorpayWebhook: webhookSecret must be a non-empty string',
    );
  }
  if (!Buffer.isBuffer(input.rawBody) || bodyBytes === 0) {
    return { ok: false, rejection: { ...base, reason: 'empty-body' } };
  }
  // Checked BEFORE hashing: an unauthenticated caller must not be able to
  // choose how much work we do.
  if (bodyBytes > MAX_WEBHOOK_BODY_BYTES) {
    return { ok: false, rejection: { ...base, reason: 'body-too-large' } };
  }
  if (!signaturePresent) {
    return { ok: false, rejection: { ...base, reason: 'missing-signature' } };
  }
  if (!signatureWellFormed) {
    return { ok: false, rejection: { ...base, reason: 'malformed-signature' } };
  }

  if (!verifyRazorpayWebhookSignature(input.rawBody, header, input.webhookSecret)) {
    return { ok: false, rejection: { ...base, reason: 'bad-signature' } };
  }

  return {
    ok: true,
    verified: { rawBody: input.rawBody, receivedAt } as unknown as VerifiedWebhook,
  };
}
