-- 0007_webhook_boundary
-- =======================================================================
-- Makes the webhook trust boundary a property of the SCHEMA rather than
-- a property of whoever writes the handler.
--
-- The problem this closes: webhook_events carries a `payload JSONB NOT
-- NULL` and a `signature_valid BOOLEAN NOT NULL`. A nullable-signature
-- column only makes sense if invalid-signature events are stored, so the
-- table was quietly inviting the natural implementation — insert first,
-- verify second — which hands any host on the internet an unbounded,
-- unauthenticated JSONB write primitive, and stores attacker-chosen text
-- in a table support staff read.
--
-- Two changes, both additive:
--
--   1. webhook_events may only ever hold VERIFIED events.
--   2. Rejected attempts get their own table that is structurally
--      incapable of holding a payload — there is no column for one.
-- =======================================================================


-- ---- 1. webhook_events is for verified events only ---------------------
--
-- The column stays (Prisma's model still declares it, and it documents
-- the intent at the row level) but it can now only ever be true. An
-- insert-then-verify handler fails loudly on its first request instead of
-- silently filling the table.

ALTER TABLE "webhook_events"
    DROP CONSTRAINT IF EXISTS "webhook_events_signature_valid_only";
ALTER TABLE "webhook_events"
    ADD CONSTRAINT "webhook_events_signature_valid_only"
    CHECK ("signature_valid" = true);


-- ---- 2. Rejections, with nowhere to put a payload ----------------------
--
-- Every column here is either generated by us or a bounded measurement of
-- the request. Nothing is copied out of the body, and there is no column
-- that could hold it if someone tried — which is the point. Observability
-- of rejected attempts costs a row of metadata, not a copy of whatever an
-- attacker decided to POST.
--
-- Deliberately NOT here: the body, any header verbatim, the signature
-- value, and anything parsed from the payload (event id, event name,
-- order id). All of those are attacker-chosen on a rejected request; an
-- event id read from an unverified body is not an event id, it is a
-- string someone sent us.

CREATE TABLE "webhook_rejections" (
    "id"                TEXT NOT NULL,
    "provider"          TEXT NOT NULL DEFAULT 'razorpay',
    "received_at"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Our classification of why we refused. A closed set, not free text.
    "reason"            TEXT NOT NULL,

    -- A number we measured, not content we copied.
    "body_bytes"        INTEGER NOT NULL,

    -- Whether a signature header was present at all, and whether it was
    -- even the right shape. Booleans about the request, never its value:
    -- storing the signature an attacker sent would be storing their data
    -- and would help nobody.
    "signature_present" BOOLEAN NOT NULL,
    "signature_well_formed" BOOLEAN NOT NULL,

    -- Network metadata, length-capped to an IPv6 maximum so a forged
    -- forwarding header cannot turn this into a text dump.
    "source_ip"         TEXT,

    "created_at"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_rejections_pkey" PRIMARY KEY ("id"),

    CONSTRAINT "webhook_rejections_reason_known" CHECK (
        "reason" IN (
            'missing-signature',
            'malformed-signature',
            'bad-signature',
            'empty-body',
            'body-too-large'
        )
    ),
    CONSTRAINT "webhook_rejections_body_bytes_nonneg" CHECK ("body_bytes" >= 0),
    CONSTRAINT "webhook_rejections_source_ip_len"
        CHECK ("source_ip" IS NULL OR length("source_ip") <= 45)
);

CREATE INDEX "webhook_rejections_received_at_idx" ON "webhook_rejections"("received_at");
CREATE INDEX "webhook_rejections_reason_idx" ON "webhook_rejections"("reason");
